# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-25 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'permissions': (('add_space_member', 'Add new member to this Space'),)},
        ),
    ]
