# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-29 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20151025_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'permissions': (('access_space', 'Access this Space'), ('add_space_member', 'Add new member to this Space'))},
        ),
    ]
